### ISSUE TITLE
cannot call from outside of portdir

### ISSUE THREAD

**Issue by prometheanfire** [alunduil/etest#56]
etest /usr/portage/dev-python/stevedore/stevedore-1.3.0.ebuild 
etest.overlay.InvalidOverlayError: not in a valid ebuild repository directory

**Comment by alunduil** [comment]
You can actually.  I'll have to see why it thinks your /usr/portage isn't a valid repository.  

What does ``cat /usr/portage/metadata/layout.conf`` say?

See this code to see how I detect repositories: https://github.com/alunduil/etest/blob/master/etest/overlay.py

**Comment by prometheanfire** [comment]
# This went live Wednesday, July 4, 2012 at 10:00 UTC
    # For more details, please see: http://archives.gentoo.org/gentoo-dev-announce/msg_00000.xml
    # and/or GLEP 59.
    manifest-hashes = SHA256 SHA512 WHIRLPOOL
    
    # Bug #470670 - gentoo's council says to deprecate EAPIs 1 and 2.
    # 2014-02-25 council meeting deprecated EAPIs 0 and 3.
    eapis-deprecated = 0 1 2 3
    
    # Bug #337853 - gentoo's council says to enable
    # --echangelog by default for the "gentoo" repo
    update-changelog = true
    
    # Make egencache generate newer (more reliable)
    # md5-dict cache format (see bug #409445).
    # NOTE: list md5-dict first so clients prefer it
    # INFRA NOTE: Format 'pms' was removed on Aug 6 2012. (Announced prior as Aug 1
    # 2012 was the removal date)
    cache-formats = md5-dict
    
    # Support for implicit masters is deprecated, so we need to explicitly
    # specify that this repo does not dependent on any masters, in order
    # to distinguish it from repos that rely on the deprecated behavior.
    masters =

**Comment by alunduil** [comment]
Oh!  I see your problem.  You definitely are not running etest in the right directory.  I bet if you ran repoman that way you'd get an error as well.
