### ISSUE TITLE
Move docker build system to a subcommand

### ISSUE THREAD

**Issue by LinoBigatti** [alunduil/etest#89]
Currently the docker build system is a messy bash script. We should make it a subcommand of etest (`etest build`)

CC: @alunduil

**Comment by alunduil** [comment]
As I mentioned on the pull request, I now think we should make this a separate command next to etest.  Does that make things simpler so should I still submit a pull request with a stub command we can put that shell script into?  We can also land the shell script and I can do the pull request for this after landing your big change.

**Comment by LinoBigatti** [comment]
I think thats OK. However, we will need to make changes to the build enviroment accordingly. If you make a stub command in a new branch I can figure out the PR nesting required to integrate it into #88

**Comment by alunduil** [comment]
> I think thats OK. However, we will need to make changes to the build enviroment accordingly. If you make a stub command in a new branch I can figure out the PR nesting required to integrate it into #88

It should just be a rebase once landed so no nesting necessary.

**Comment by alunduil** [comment]
@LinoBigatti, if you want to rebase your pull request, we can merge it and keep cleaning things up to get momentum back.  If you prefer removing it altogether instead, close this issue.

**Comment by LinoBigatti** [comment]
I think cleaning it progressively is the better option, especially since we are both probably a bit rusty on the codebase. It will give us some time to get used to it and gain momentum. I will check everything works ok and then do a rebase.
