### ISSUE TITLE
Adding a new dockerhub organization for image storing.

### ISSUE THREAD

**Issue by LinoBigatti** [alunduil/etest#96]
A new [dockerhub](hub.docker.com) organization or team would be great to manage image updates and such. We could also use it to manage automatic image building.

**Comment by alunduil** [comment]
Sorry for the long silence, life got messy for a bit.

I've created a new dockerhub organisation at:
https://hub.docker.com/orgs/ebuildtest

Let me know which username you'd like me to add over matrix.
